### ISSUE TITLE
Dolphin Relicensing

### ISSUE THREAD

**Issue by lioncash** [mirror/dolphin-emu#47]
Hey there again. Just wondering if I could get a yes or no from you on the topic of re-licensing Dolphin from "GPLv2" over to "GPLv2 or later". 

Here's the two spreadsheets related to this. One for those who have agreed/disagreed to it already, and one on the details of why this would be occurring.
- [Agreement List](https://docs.google.com/spreadsheets/d/1QeZYHduULTSZWUgMg_uUghIWqsCuTvvW5Z2YCfHM7oM/edit#gid=0)
- [Details](https://docs.google.com/document/d/1bRQO9oF9ewj7hdczz23oc6CS_g0Uk97_9qNrSqGCMiY/edit#heading=h.5gvm9kfdly25)

If anything else is needed, I suppose you could just pop into the dolphin-dev channel on freenode and things can be clarified.

**Comment by john-peterson** [comment]
i don't care

u can relicense to WTFPL as far as i care

**Comment by lioncash** [comment]
Nice, thanks for the response!
